### ISSUE TITLE
I'm judging you

### ISSUE THREAD

**Issue by webdesserts** [bstyne3/myPage#1]
o_o

**Comment by bstyne3** [comment]
im guessing you see things you dont like lol...

**Comment by webdesserts** [comment]
Haha, no, but I was gunna check the site out once I got the chance. Feedback welcome?

**Comment by bstyne3** [comment]
absolutely, just remember this is my first true website im creating outside of UMHB courses i took which had basically no styling in them lol
EDIT: AND it is far from complete

**Comment by webdesserts** [comment]
I'll open a few issues that are mostly going to be suggestions. Feel free to do what you want with them :)

Anyway I'm closing this non-issue lol.
